name = "qiportal-client"
type = "javascript"

account_id = "6c0d95a612e676663f8c1461a6c88bad"  # ← your Cloudflare account ID
workers_dev = false
compatibility_date = "2025-08-22"

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "npm run build"

[env.production]
route = "https://qially.cloudflareaccess.com/*"
zone_id = "" # Optional, only needed if using Workers + DNS
