# .github/workflows/build.yml
name: Build KB Sites
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client:
          - { slug: "builtbyrays", org: "274909a9-df10-49e1-9b0e-5a7c7f86dddf" }
          - { slug: "qially",      org: "3c5f857f-54a2-4c3f-b41d-b0b34fec7db2" }
          - { slug: "zaitullahk",  org: "69a343d1-9bc2-4cc1-8474-21ee3a7afb1d" }
          - { slug: "rosalucas",   org: "5be6a24b-56a9-409c-9656-7e924501b855" }
          - { slug: "luisaltamirano", org: "58ca62aa-cd34-474b-9bcb-86cb165c574b" }
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: { version: 9 }
      - run: pnpm i --frozen-lockfile
      - name: Export content
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          ORG_ID: ${{ matrix.client.org }}
          OUT: apps/kb-${{ matrix.client.slug }}/content
        run: node packages/exporter/export.mjs
      - name: Build Quartz
        run: pnpm --filter kb-${{ matrix.client.slug }} build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: kb-${{ matrix.client.slug }}
          directory: apps/kb-${{ matrix.client.slug }}/public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
